# Generated by Django 4.1.7 on 2023-08-11 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myweatherapp", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="history", name="data",),
        migrations.AddField(
            model_name="history",
            name="location",
            field=models.TextField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="history",
            name="temperature",
            field=models.TextField(max_length=100, null=True),
        ),
    ]
