# Generated by Django 4.1.7 on 2023-08-11 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myweatherapp", "0002_remove_history_data_history_location_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="history",
            name="location",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="history",
            name="temperature",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
