# Generated by Django 4.1.7 on 2023-08-11 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myweatherapp", "0003_alter_history_location_alter_history_temperature"),
    ]

    operations = [
        migrations.RemoveField(model_name="history", name="updated",),
        migrations.AlterField(
            model_name="history",
            name="created",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
